"""Se reconfiguró la estructura de Many to One a One(user) to Many(bines)

Revision ID: 6476080f01f7
Revises: 64378d268038
Create Date: 2022-07-09 11:09:49.280413

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6476080f01f7'
down_revision = '64378d268038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bienes', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bienes', 'user', ['usuario_id'], ['id'])
    op.drop_constraint('user_ibfk_1', 'user', type_='foreignkey')
    op.drop_column('user', 'bien_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bien_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_ibfk_1', 'user', 'bienes', ['bien_id'], ['id'])
    op.drop_constraint(None, 'bienes', type_='foreignkey')
    op.drop_column('bienes', 'usuario_id')
    # ### end Alembic commands ###
